### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by i240c** [kr8gz/PlayerStatistics#1]
Hello, is there a 1.21 update planned for this mod?

**Comment by kr8gz** [comment]
Hello,
thank you for your interest in my mod! I definitely intend to continue developing and maintaining this mod. I am pretty busy right now though, so unfortunately it won't happen anytime soon :(

**Comment by kr8gz** [comment]
Hello @MJRamon, please check out the [newest release](https://modrinth.com/mod/playerstatistics/version/0.1.1)!
About an update for 1.21: Since Minecraft 1.20.5 was already a large update, this will take a lot longer – please be patient :)

**Comment by kr8gz** [comment]
@MJRamon sorry for the disappointment lol, silly me didn't think of testing compatibility both ways before releasing – I am now figuring out a new strategy to support different versions within the same project. The code itself doesn't require any further changes, but sadly dependencies rely heavily on the Minecraft version :/

**Comment by kr8gz** [comment]
@MJRamon I'm curious, what kind of project? Also yeah I can try to make a one-off thing tomorrow 🙂

**Comment by kr8gz** [comment]
Hello @MJRamon, please try [this release](https://modrinth.com/mod/playerstatistics/version/0.1.1+1.20)!

**Comment by kr8gz** [comment]
Oh yeah that's an embarrassing oversight, good catch

**Comment by kr8gz** [comment]
Hello @i240c, I have released a version for 1.21: https://modrinth.com/mod/playerstatistics/version/0.1.2+1.21

> When starting a fresh server without any stats, mod fails
@MJRamon this issue has been fixed with the new release as well.

Please test the new versions – if there are no problems, this issue can be closed :)

**Comment by txmazing** [comment]
Hey, will version 1.21.3 be supported in the near future?

**Comment by kr8gz** [comment]
> Hey, will version 1.21.3 be supported in the near future?
Hello, Fabric 1.21.4 was just released. I will be working on an update soon :)

**Comment by kr8gz** [comment]
Hey @txmazing, please check out this release:
https://modrinth.com/mod/playerstatistics/version/0.2.1+1.21.2
