### ISSUE TITLE
Formatting support

### ISSUE THREAD

**Issue by BeastlyDude1234** [kr8gz/PlayerStatistics#5]
Could you possibly add a config file with all of the messages formatting so I could change them to fit the theme of my server?

**Comment by kr8gz** [comment]
Should be simple enough — will try adding after I'm back from my holidays :)

**Comment by kr8gz** [comment]
Please take a look at this new [config file](https://github.com/kr8gz/PlayerStatistics/blob/9f8ee795947aa21a15083b6a8ddf3df26db77686/src/main/resources/config.toml) and let me know what you think of it!

**Comment by BeastlyDude1234** [comment]
That looks like it should work. I'll try it out next time I play. Just curious, what color system is it using? (like rgb, hex). I've never seen it before.

**Comment by kr8gz** [comment]
I'll document it and release the new version tomorrow probably 🙂
Those color codes are just hex numbers

**Comment by BeastlyDude1234** [comment]
Alright, thank you.
